services:
  browser-use-webui:
    env_file: .env
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6080:6080" # noVNC web interface
      - "5900:5900" # VNC port
      - "9222:9222" # Chrome remote debugging port
      - "7788:7788" # FastAPI port
    environment:
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - DEEPSEEK_ENDPOINT=${DEEPSEEK_ENDPOINT}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - BROWSER_USE_LOGGING_LEVEL=${BROWSER_USE_LOGGING_LEVEL}
      - ANONYMIZED_TELEMETRY=false
      - CHROME_PATH=/usr/bin/google-chrome
      - CHROME_USER_DATA=/app/data/chrome_data
      - CHROME_PERSISTENT_SESSION=${CHROME_PERSISTENT_SESSION}
      - CHROME_DEBUGGING_PORT=9222
      - CHROME_DEBUGGING_HOST=0.0.0.0
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - RESOLUTION=${RESOLUTION}
      - RESOLUTION_WIDTH=${RESOLUTION_WIDTH}
      - RESOLUTION_HEIGHT=${RESOLUTION_HEIGHT}
      - VNC_PASSWORD=${VNC_PASSWORD}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/dbus:/run/dbus
    restart: unless-stopped
    shm_size: "2gb"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5900"]
      interval: 10s
      timeout: 5s
      retries: 3
