---
name: lint

on:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - main
  # Run superlinter on pull request events
  pull_request:

# Declare default permissions as read-only
permissions: read-all

jobs:
  super-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      # - name: 🧹 run superlinter
      #   uses: super-linter/super-linter@12150456a73e248bdc94d0794898f94e23127c88 # v7.4.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     LINTER_RULES_PATH: ".github/linters"
      #     MARKDOWN_CONFIG_FILE: ".markdownlint.yml"
      #     YAML_CONFIG_FILE: ".yamllint.yml"
      #     VALIDATE_ALL_CODEBASE: false
      #     VALIDATE_MARKDOWN_PRETTIER: false
      #     VALIDATE_YAML_PRETTIER: false
      #     VALIDATE_NATURAL_LANGUAGE: false
      #     MULTI_STATUS: false
